"""Configuration package (PROJECT_DESIGN section 45-47)."""

from vcp_scanner.config.loader import compute_config_hash, load_scanner_config
from vcp_scanner.config.models import (
    ClassificationConfig,
    DataConfig,
    LoggingConfig,
    MonitoringConfig,
    NormalizationBounds,
    RSConfig,
    ScannerConfig,
    ScoringConfig,
    StageConfig,
    StrategyConfig,
    TierClassificationConfig,
    TrendTemplateConfig,
    UniverseConfig,
    VCPConfirmationConfig,
    VCPContractionCountConfig,
    VCPPivotConfig,
    VCPSwingConfig,
    VCPThresholdsConfig,
    VCPVolatilityConfig,
    VCPVolumeConfig,
)

__all__ = [
    "ClassificationConfig",
    "DataConfig",
    "LoggingConfig",
    "MonitoringConfig",
    "NormalizationBounds",
    "RSConfig",
    "ScannerConfig",
    "ScoringConfig",
    "StageConfig",
    "StrategyConfig",
    "TierClassificationConfig",
    "TrendTemplateConfig",
    "UniverseConfig",
    "VCPConfirmationConfig",
    "VCPContractionCountConfig",
    "VCPPivotConfig",
    "VCPSwingConfig",
    "VCPThresholdsConfig",
    "VCPVolatilityConfig",
    "VCPVolumeConfig",
    "compute_config_hash",
    "load_scanner_config",
]
